{"changes": {"assignee_account_id": {"new": "557058:869c02bb-b246-4cdc-9db3-0064e8add185", "old": ""}, "assignee": {"new": "hugomatic", "old": "None"}}, "links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/8/changes/2614861.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/8#comment-2614861"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/8.json"}}, "type": "issue", "id": 8, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "title": "Need to catch crashed tests"}, "created_on": "2012-12-13T02:46:13.875192+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "message": {"raw": "@hugomatic, can you look into making the test output file names predictable?  Then, if you want, I can help with integrating the test-result-checker (though you can probably get that working yourself).\r\n\r\nUpping priority because we've already seen where this problem caused an erroneous success result.", "markup": "markdown", "html": "<p>@hugomatic, can you look into making the test output file names predictable?  Then, if you want, I can help with integrating the test-result-checker (though you can probably get that working yourself).</p>\n<p>Upping priority because we've already seen where this problem caused an erroneous success result.</p>", "type": "rendered"}, "type": "issue_change", "id": 2614861}