{"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/142/comments/4789521.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/142#comment-4789521"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/142.json"}}, "type": "issue", "id": 142, "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "title": "Can't start run"}, "content": {"raw": "After reboot, X was not running.  `initctl start lightdm` brought it up.  I was then able to run a task.\n\nNot sure what happened here, but constellation 16 seems to be working properly again.", "markup": "markdown", "html": "<p>After reboot, X was not running.  <code>initctl start lightdm</code> brought it up.  I was then able to run a task.</p>\n<p>Not sure what happened here, but constellation 16 seems to be working properly again.</p>", "type": "rendered"}, "created_on": "2013-06-12T03:53:51.749834+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 4789521}