{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "links": {"attachments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/145/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/145.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/145/watch"}, "comments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/145/comments_page=1.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/145/tasks-arent-entered-in-order"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/145/vote"}}, "reporter": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "title": "tasks aren't entered in order", "component": null, "votes": 0, "watches": 0, "content": {"raw": "We've seen a couple of instance where `bin/send_tasks.py` does not preserve the order on the `task_sequence` in the YAML file it's given.  It just happened on constellation 09 when loading 300 tasks that should have been a repeating sequence 1,2,3.  Not sure whether some got lost, or whether they're all there and just out of order.", "markup": "markdown", "html": "<p>We've seen a couple of instance where <code>bin/send_tasks.py</code> does not preserve the order on the <code>task_sequence</code> in the YAML file it's given.  It just happened on constellation 09 when loading 300 tasks that should have been a repeating sequence 1,2,3.  Not sure whether some got lost, or whether they're all there and just out of order.</p>", "type": "rendered"}, "assignee": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "state": "resolved", "version": null, "edited_on": null, "created_on": "2013-06-14T06:16:02.288704+00:00", "milestone": null, "updated_on": "2013-06-14T07:08:49.164703+00:00", "type": "issue", "id": 145}