{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "links": {"attachments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/19/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/19.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/19/watch"}, "comments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/19/comments_page=1.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/19/aws-reports-instance-as-missing"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/19/vote"}}, "reporter": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "title": "AWS reports instance as missing", "component": null, "votes": 0, "watches": 0, "content": {"raw": "This error happened while trying to set the tags on the field computer: AWS reported the instance to be inexistent. The instance does exist, however (see image), and this it the first report of such a problem.\r\n\r\nLOG: cloudsimd.py launch error: EC2ResponseError: 400 Bad Request\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-ec9bf39c' does not exist</Message></Error></Errors><RequestID>c77fc68d-506d-4281-b896-0939ac40f6f7</RequestID></Response>\r\nLOG: traceback:  Traceback (most recent call last):\r\n  File \"/var/cloudsimd/cloudsimd.py\", line 111, in launch\r\n    launch(username, constellation_name, tags, credentials_ec2, constellation_directory)\r\n  File \"/var/cloudsimd/launchers/vpc_trio.py\", line 137, in launch\r\n    CONFIGURATION)\r\n  File \"/var/cloudsimd/launchers/vpc_trio.py\", line 612, in trio_launch\r\n    ec2conn.create_tags([ robot_aws_id ], robot_tags)\r\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 3203, in create_tags\r\n    return self.get_status('CreateTags', params, verb='POST')\r\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1019, in get_status\r\n    raise self.ResponseError(response.status, response.reason, body)\r\nEC2ResponseError: EC2ResponseError: 400 Bad Request\r\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<Response><Errors><Error><Code>InvalidInstanceID.NotFound</Code><Message>The instance ID 'i-ec9bf39c' does not exist</Message></Error></Errors><RequestID>c77fc68d-506d-4281-b896-0939ac40f6f7</RequestID></Response>", "markup": "markdown", "html": "<p>This error happened while trying to set the tags on the field computer: AWS reported the instance to be inexistent. The instance does exist, however (see image), and this it the first report of such a problem.</p>\n<p>LOG: cloudsimd.py launch error: EC2ResponseError: 400 Bad Request\n&lt;?xml version=\"1.0\" encoding=\"UTF-8\"?&gt;\n&lt;Response&gt;&lt;Errors&gt;&lt;Error&gt;&lt;Code&gt;InvalidInstanceID.NotFound&lt;/Code&gt;&lt;Message&gt;The instance ID 'i-ec9bf39c' does not exist&lt;/Message&gt;&lt;/Error&gt;&lt;/Errors&gt;&lt;RequestID&gt;<a href=\"#!/osrf/cloudsim-legacy/commits/c77fc68d\" rel=\"nofollow\" class=\"ap-connect-link\">c77fc68d</a>-506d-4281-b896-0939ac40f6f7&lt;/RequestID&gt;&lt;/Response&gt;\nLOG: traceback:  Traceback (most recent call last):\n  File \"/var/cloudsimd/cloudsimd.py\", line 111, in launch\n    launch(username, constellation_name, tags, credentials_ec2, constellation_directory)\n  File \"/var/cloudsimd/launchers/vpc_trio.py\", line 137, in launch\n    CONFIGURATION)\n  File \"/var/cloudsimd/launchers/vpc_trio.py\", line 612, in trio_launch\n    ec2conn.create_tags([ robot_aws_id ], robot_tags)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 3203, in create_tags\n    return self.get_status('CreateTags', params, verb='POST')\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1019, in get_status\n    raise self.ResponseError(response.status, response.reason, body)\nEC2ResponseError: EC2ResponseError: 400 Bad Request\n&lt;?xml version=\"1.0\" encoding=\"UTF-8\"?&gt;\n&lt;Response&gt;&lt;Errors&gt;&lt;Error&gt;&lt;Code&gt;InvalidInstanceID.NotFound&lt;/Code&gt;&lt;Message&gt;The instance ID 'i-ec9bf39c' does not exist&lt;/Message&gt;&lt;/Error&gt;&lt;/Errors&gt;&lt;RequestID&gt;<a href=\"#!/osrf/cloudsim-legacy/commits/c77fc68d\" rel=\"nofollow\" class=\"ap-connect-link\">c77fc68d</a>-506d-4281-b896-0939ac40f6f7&lt;/RequestID&gt;&lt;/Response&gt;</p>", "type": "rendered"}, "assignee": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "state": "wontfix", "version": null, "edited_on": null, "created_on": "2013-02-05T02:59:47.323960+00:00", "milestone": null, "updated_on": "2013-03-13T16:24:48.916756+00:00", "type": "issue", "id": 19}