{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/cloudsim-legacy.json"}, "html": {"href": "#!/osrf/cloudsim-legacy"}, "avatar": {"href": "data/bytebucket.org/ravatar/{e799e7f6-0caa-464a-97f8-8605a37ebfb1}ts=python"}}, "type": "repository", "name": "cloudsim-legacy", "full_name": "osrf/cloudsim-legacy", "uuid": "{e799e7f6-0caa-464a-97f8-8605a37ebfb1}"}, "links": {"attachments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/54/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/cloudsim-legacy/issues/54.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/54/watch"}, "comments": {"href": "data/repositories/osrf/cloudsim-legacy/issues/54/comments_page=1.json"}, "html": {"href": "#!/osrf/cloudsim-legacy/issues/54/timeout-on-creation-of-cloudsim"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/cloudsim-legacy/issues/54/vote"}}, "reporter": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "title": "timeout on creation of cloudsim", "component": null, "votes": 0, "watches": 0, "content": {"raw": "I had the following error when trying to launch a new CloudSim machine, using cloudsim-1.2.0 (private details removed from command line):\r\n\r\n    $ ./cloudsim-1.2.0/bin/create_cloudsim.py <address> <key> <secret-key> <zone>\r\n    ./cloudsim-1.2.0/inside/cgi-bin\r\n    ./cloudsim-1.2.0/cloudsimd/launchers\r\n    ./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py\r\n    Traceback (most recent call last):\r\n      File \"./cloudsim-1.2.0/bin/create_cloudsim.py\", line 51, in <module>\r\n        machine = cloudsim.cloudsim_bootstrap(username, tmp_fname.name)\r\n      File \"./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py\", line 446, in cloudsim_bootstrap\r\n      File \"./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py\", line 249, in launch\r\nlaunch_utils.launch.LaunchException: timeout while waiting for EC2 machine(s) cloudsim_c6b04475a\r\n\r\nIt looks like, from the AWS Console, that the machine was created, but never received any tags or other provisioning.\r\n\r\nI tried the same command again, about 30 minutes later (after trying to debug the failed launch), and it succeeded.\r\n\r\nPerhaps a timeout should be adjusted.", "markup": "markdown", "html": "<p>I had the following error when trying to launch a new CloudSim machine, using cloudsim-1.2.0 (private details removed from command line):</p>\n<div class=\"codehilite\"><pre><span></span>$ ./cloudsim-1.2.0/bin/create_cloudsim.py &lt;address&gt; &lt;key&gt; &lt;secret-key&gt; &lt;zone&gt;\n./cloudsim-1.2.0/inside/cgi-bin\n./cloudsim-1.2.0/cloudsimd/launchers\n./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py\nTraceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n  File <span class=\"s2\">&quot;./cloudsim-1.2.0/bin/create_cloudsim.py&quot;</span>, line <span class=\"m\">51</span>, in &lt;module&gt;\n    <span class=\"nv\">machine</span> <span class=\"o\">=</span> cloudsim.cloudsim_bootstrap<span class=\"o\">(</span>username, tmp_fname.name<span class=\"o\">)</span>\n  File <span class=\"s2\">&quot;./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py&quot;</span>, line <span class=\"m\">446</span>, in cloudsim_bootstrap\n  File <span class=\"s2\">&quot;./cloudsim-1.2.0/cloudsimd/launchers/cloudsim.py&quot;</span>, line <span class=\"m\">249</span>, in launch\n</pre></div>\n\n\n<p>launch_utils.launch.LaunchException: timeout while waiting for EC2 machine(s) cloudsim_c6b04475a</p>\n<p>It looks like, from the AWS Console, that the machine was created, but never received any tags or other provisioning.</p>\n<p>I tried the same command again, about 30 minutes later (after trying to debug the failed launch), and it succeeded.</p>\n<p>Perhaps a timeout should be adjusted.</p>", "type": "rendered"}, "assignee": null, "state": "duplicate", "version": null, "edited_on": null, "created_on": "2013-02-26T02:27:23.074782+00:00", "milestone": null, "updated_on": "2013-03-01T21:43:40.818492+00:00", "type": "issue", "id": 54}